name: AutoUpdates

on:
#  schedule:
#    - cron:  '*/5 * * * *'
  push:
    branches: [ master ]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Run update script
      run: |
        echo "TEST update"
        pwd && ls
        ./update.sh
        echo "UPDATED!"
        cat data
        git status
